(async()=>{'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const recipes=await fetch('data/recipes.json').then(r=>r.json());
const seedElements=await fetch('data/elements.json').then(r=>r.json());
const icons={Mud:'◒',Mist:'≋',Lava:'◉',Steam:'♨',Dust:'⁙',Stone:'⬟',Pond:'◯',Energy:'ϟ',Sand:'∴',Glass:'◇',Clay:'⬢',Brick:'▰',Soil:'▨',Plant:'♧',Tree:'♠',Wood:'▥',Reeds:'〽',Moss:'❧','Primordial Life':'✧',Fish:'><>',Creature:'♞',Insect:'✥',Human:'♙','Sharp Stone':'◢',Tool:'⚒',Plank:'▬',Charcoal:'●','Hot Stone':'◉',Pot:'∪',Wall:'▦',Shelter:'⌂','Campfire Base':'⌄',Campfire:'♨','Glass Pane':'▱',Rope:'§',Raft:'▤',Seeds:'⁘',Crops:'≋',Food:'◈','Cooked Fish':'⋈',Settler:'♟','Metal Ore':'✦',Metal:'⬡','Advanced Tool':'⚙',Electricity:'ϟ'};
const colors={Nature:'#69a75f',Materials:'#a9784c',Life:'#d66f77',Tools:'#637f83',Structures:'#ae7544',Technology:'#bb8ee8',Primordial:'#64aeca'};
const elements={...seedElements}; recipes.forEach(r=>elements[r.result]={icon:icons[r.result]||'✦',color:colors[r.category],category:r.category,description:r.text});
const key=(a,b)=>[a,b].sort().join('|'), recipeMap=new Map(recipes.map(r=>[key(r.a,r.b),r]));
const TOTAL=recipes.length, SAVE='alchemy-island-v01'; let state, selected=[], activeCategory='All', journalCategory='All', running=false, last=0, toastTimer, audio;
const defaults=()=>({discovered:['Air','Earth','Fire','Water'],known:[],effects:[],attempts:0,success:0,failed:0,pos:{x:0,y:155},settings:{sound:true,motion:false},finale:false,tutorial:true});
function load(){try{return {...defaults(),...JSON.parse(localStorage.getItem(SAVE)||'null')}}catch{return defaults()}}
function save(){localStorage.setItem(SAVE,JSON.stringify(state))}
function hasSave(){return !!localStorage.getItem(SAVE)}
function tone(type='select'){if(!state?.settings.sound)return; audio??=new(window.AudioContext||window.webkitAudioContext)(); const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);let now=audio.currentTime, f={select:330,fail:120,success:523,discover:659,milestone:392,electric:880}[type]||330;o.frequency.setValueAtTime(f,now);if(type==='discover')o.frequency.exponentialRampToValueAtTime(f*1.7,now+.35);if(type==='electric')o.type='sawtooth';g.gain.setValueAtTime(.001,now);g.gain.exponentialRampToValueAtTime(.12,now+.02);g.gain.exponentialRampToValueAtTime(.001,now+(type==='milestone'?1:.35));o.start(now);o.stop(now+(type==='milestone'?1:.4))}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),1800)}
function start(continueGame=false){state=continueGame?load():defaults();if(!continueGame)save();$('#titleScreen').classList.add('hidden');$('#hud,#alchemy').forEach?.(()=>{});$('#hud').classList.remove('hidden');$('#alchemy').classList.remove('hidden');if(matchMedia('(pointer:coarse)').matches)$('#joystick').classList.remove('hidden');running=true;renderElements();updateContinue();if(state.tutorial&&!continueGame)opening();}
function updateContinue(){const b=$('#continueBtn');b.disabled=!hasSave()}
async function opening(){const box=$('#opening'),p=$('#openingText');box.classList.remove('hidden');for(const text of ['You remember nothing.','Only four forces answer you.','AIR · EARTH · FIRE · WATER','Combine them.\n\nEARTH + WATER = MUD']){p.innerText=text;await new Promise(r=>setTimeout(r,2100))}box.classList.add('hidden');toast('Try Earth + Water');}
function renderElements(){const cats=['All','Primordial','Nature','Life','Materials','Tools','Structures','Technology'];$('#categories').innerHTML=cats.map(c=>`<button class="${c===activeCategory?'active':''}" data-cat="${c}">${c}</button>`).join('');const list=state.discovered.filter(n=>activeCategory==='All'||elements[n].category===activeCategory);$('#elements').innerHTML=list.map(n=>`<div class="element" data-element="${n}" title="${elements[n].description}"><span class="ico" style="color:${elements[n].color}">${elements[n].icon}</span><b>${n}</b></div>`).join('');$$('.element').forEach(el=>el.onclick=()=>selectElement(el.dataset.element));$$('#categories button').forEach(b=>b.onclick=()=>{activeCategory=b.dataset.cat;tone();renderElements()});renderSelected();}
function selectElement(n){tone();if(selected.length>=2)selected=[];selected.push(n);$('#hint').textContent=selected.length===1?'Choose a second element.':'Ready to combine.';renderSelected()}
function renderSelected(){$$('.slot').forEach((s,i)=>{const n=selected[i];s.classList.toggle('filled',!!n);s.innerHTML=n?`<span style="font-size:22px;color:${elements[n].color}">${elements[n].icon}</span><b>${n}</b>`:'Choose';s.onclick=()=>{selected.splice(i,1);renderSelected()}});$('#combineBtn').disabled=selected.length!==2}
function combine(){if(selected.length!==2)return;state.attempts++;const r=recipeMap.get(key(...selected));if(!r){state.failed++;tone('fail');$('#alchemy').animate?.([{transform:'translateX(0)'},{transform:'translateX(-6px)'},{transform:'translateX(6px)'},{transform:'translateX(0)'}],{duration:220});$('#hint').textContent='Nothing happens…';toast('Nothing happens…');selected=[];renderSelected();save();return}state.success++;const first=!state.discovered.includes(r.result);if(first){state.discovered.push(r.result);state.known.push(key(r.a,r.b));if(r.worldEffect&&!state.effects.includes(r.worldEffect))state.effects.push(r.worldEffect);save();renderElements();showDiscovery(r)}else{tone('success');toast(`${r.a} + ${r.b} → ${r.result}`)}selected=[];renderSelected();save()}
function showDiscovery(r){tone(r.worldEffect?'milestone':'discover');$('#discoveryIcon').textContent=elements[r.result].icon;$('#discoveryIcon').style.color=elements[r.result].color;$('#discoveryName').textContent=r.result.toUpperCase();$('#discoveryText').textContent=`“${r.text}”`;$('#discovery').classList.remove('hidden');spawnBurst();if(r.result==='Electricity')setTimeout(finale,1000)}
function finale(){tone('electric');state.finale=true;save();$('#discovery').classList.add('hidden');$('#finale').classList.remove('hidden')}
function openJournal(){renderJournal();$('#journal').classList.remove('hidden')}
function renderJournal(){const cats=['All','Primordial','Nature','Life','Materials','Tools','Structures','Technology'];$('#journalTabs').innerHTML=cats.map(c=>`<button data-jcat="${c}" class="${c===journalCategory?'active':''}">${c}</button>`).join('');const names=['Air','Earth','Fire','Water',...recipes.map(r=>r.result)].filter(n=>journalCategory==='All'||elements[n].category===journalCategory);$('#journalGrid').innerHTML=names.map(n=>state.discovered.includes(n)?`<div class="journal-item"><div class="ico" style="color:${elements[n].color}">${elements[n].icon}</div><b>${n}</b><small>${elements[n].description}</small></div>`:`<div class="journal-item locked">???</div>`).join('');const d=state.discovered.length-4,p=Math.round(d/TOTAL*100);$('#progressText').textContent=`${d} / ${TOTAL} · ${p}% COMPLETE`;$('#progressBar').style.width=p+'%';$('#stats').textContent=`EXPERIMENTS ${state.attempts}  ·  SUCCESSFUL ${state.success}  ·  FAILED ${state.failed}`;$$('[data-jcat]').forEach(b=>b.onclick=()=>{journalCategory=b.dataset.jcat;renderJournal()})}
// World rendering
const canvas=$('#game'),ctx=canvas.getContext('2d'),world={w:1200,h:800},keys={},particles=[];let DPR=1,joy={x:0,y:0};
function resize(){DPR=Math.min(devicePixelRatio||1,2);canvas.width=innerWidth*DPR;canvas.height=innerHeight*DPR;canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px'}addEventListener('resize',resize);resize();
function rng(i){return((Math.sin(i*982.451)*43758.5453)%1+1)%1}
function ellipse(x,y,rx,ry,fill,stroke){ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=4;ctx.stroke()}}
function drawWorld(t){const sx=canvas.width/DPR,sy=canvas.height/DPR,mobile=sx<=700,scale=Math.min(sx/(mobile?720:900),sy/620),anchorY=mobile?sy*.44:sy/2;ctx.setTransform(DPR,0,0,DPR,0,0);let g=ctx.createLinearGradient(0,0,0,sy);g.addColorStop(0,state.effects.includes('electricity')?'#183e49':'#56b8ca');g.addColorStop(1,'#0a7187');ctx.fillStyle=g;ctx.fillRect(0,0,sx,sy);ctx.save();ctx.translate(sx/2-state.pos.x*scale,anchorY-state.pos.y*scale);ctx.scale(scale,scale);
// water rings
ctx.strokeStyle='#b8f4e733';ctx.lineWidth=3;for(let i=0;i<14;i++){let y=-330+i*52+Math.sin(t/900+i)*6;ctx.beginPath();ctx.moveTo(-700,y);ctx.quadraticCurveTo(0,y+20,700,y);ctx.stroke()}
ellipse(0,0,520,345,'#e7c77e','#a7e1b0');ellipse(0,-10,450,290,'#74ad68');ellipse(-40,20,365,235,'#82b96e');
// paths/rocks
ctx.strokeStyle='#d3b674';ctx.lineWidth=24;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(-410,110);ctx.quadraticCurveTo(-90,40,300,130);ctx.stroke();for(let i=0;i<18;i++){let x=rng(i)*820-410,y=rng(i+40)*430-210;ellipse(x,y,8+rng(i+2)*9,6+rng(i+3)*7,'#7d846d','#596b5f')}
if(state.effects.includes('vegetation'))for(let i=0;i<32;i++){let a=rng(i+90)*6.28,r=80+rng(i+110)*330,x=Math.cos(a)*r,y=Math.sin(a)*r*.65;ctx.fillStyle=i%3?'#398e58':'#9dd56d';ctx.beginPath();ctx.arc(x,y,4+rng(i)*5,0,6.3);ctx.fill()}
if(state.effects.includes('trees'))for(let i=0;i<9;i++)tree(-300+i*74+(i%2)*20,-120+(i%3)*80,t,i);
if(state.effects.includes('crops'))farm(205,-95);
if(state.effects.includes('shelter'))hut(65,-155);
if(state.effects.includes('campfire'))campfire(-30,75,t);
if(state.effects.includes('raft'))raft(-430,175,t);
if(state.effects.includes('human'))person(130,35,'#d66f77',t);
if(state.effects.includes('settler'))person(165,65,'#e7b556',t+900);
if(state.effects.includes('electricity'))generator(110,-55,t);
person(state.pos.x,state.pos.y,'#e9d0a4',t,true);particles.forEach((p,i)=>{p.y-=p.v;p.life--;ctx.globalAlpha=Math.max(0,p.life/40);ellipse(p.x,p.y,p.s,p.s,p.c);ctx.globalAlpha=1;if(p.life<=0)particles.splice(i,1)});ctx.restore()}
function tree(x,y,t,i){ctx.fillStyle='#6c4328';ctx.fillRect(x-5,y,10,35);ellipse(x,y-8,25,29,i%2?'#2f7e4f':'#3f9255');ellipse(x-13,y-4,14,17,'#55a862');ellipse(x+14,y-5,14,18,'#4a9e5a')}
function hut(x,y){ctx.fillStyle='#8d562d';ctx.fillRect(x-48,y-10,96,65);ctx.fillStyle='#d59d50';ctx.beginPath();ctx.moveTo(x-62,y);ctx.lineTo(x,y-55);ctx.lineTo(x+62,y);ctx.fill();ctx.fillStyle='#382c25';ctx.fillRect(x-12,y+20,24,35);ctx.fillStyle='#87d5d2';ctx.fillRect(x+23,y+12,18,15)}
function farm(x,y){ctx.fillStyle='#765631';ctx.fillRect(x-70,y-42,140,84);for(let i=0;i<5;i++){ctx.strokeStyle='#afda63';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(x-55+i*27,y-32);ctx.lineTo(x-55+i*27,y+32);ctx.stroke()}}
function campfire(x,y,t){ctx.fillStyle='#5a4130';for(let a=0;a<6.3;a+=1.05)ellipse(x+Math.cos(a)*18,y+Math.sin(a)*9,7,5,'#6f6b5c');ctx.fillStyle='#ffbf44';ctx.beginPath();ctx.moveTo(x-10,y);ctx.quadraticCurveTo(x-18,y-30,x,y-43-Math.sin(t/100)*5);ctx.quadraticCurveTo(x+18,y-25,x+10,y);ctx.fill();ellipse(x,y-3,8,15,'#f26b3d')}
function raft(x,y,t){ctx.save();ctx.translate(x,y+Math.sin(t/500)*4);ctx.rotate(-.12);for(let i=0;i<5;i++){ctx.fillStyle='#82512f';ctx.fillRect(-35+i*15,-17,12,45)}ctx.fillStyle='#dbc88f';ctx.beginPath();ctx.moveTo(0,-65);ctx.lineTo(0,-15);ctx.lineTo(35,-20);ctx.closePath();ctx.fill();ctx.restore()}
function generator(x,y,t){ctx.strokeStyle='#3c2d24';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(x,y);ctx.quadraticCurveTo(x+80,y+50,x+145,y-5);ctx.stroke();ctx.fillStyle='#82643d';ctx.fillRect(x-22,y-20,44,42);ctx.fillStyle='#d8b94f';ctx.beginPath();ctx.arc(x,y,13,0,6.3);ctx.fill();ctx.save();ctx.translate(x,y);ctx.rotate(t/180);ctx.strokeStyle='#394d4d';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(-14,0);ctx.lineTo(14,0);ctx.moveTo(0,-14);ctx.lineTo(0,14);ctx.stroke();ctx.restore();ctx.strokeStyle='#694923';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(x+145,y);ctx.lineTo(x+145,y-55);ctx.stroke();ctx.fillStyle=Math.sin(t/130)>-.3?'#fff7a0':'#534d39';ctx.shadowBlur=25;ctx.shadowColor='#fff28a';ellipse(x+145,y-62,12,16,ctx.fillStyle);ctx.shadowBlur=0}
function person(x,y,c,t,player=false){ctx.save();ctx.translate(x,y);let bob=Math.sin(t/180)*2;ellipse(0,-19+bob,9,10,'#c98c62');ctx.fillStyle=c;ctx.fillRect(-8,-10+bob,16,25);ctx.strokeStyle='#3f3a35';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(-4,14+bob);ctx.lineTo(-7,27);ctx.moveTo(4,14+bob);ctx.lineTo(7,27);ctx.stroke();if(player&&state.effects.includes('advanced_tool')){ctx.strokeStyle='#d6d9cc';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(10,-4);ctx.lineTo(20,20);ctx.stroke();ctx.fillStyle='#adb8b6';ctx.fillRect(7,-8,12,7)}ctx.restore()}
function spawnBurst(){for(let i=0;i<28;i++)particles.push({x:state.pos.x+(rng(i)-.5)*60,y:state.pos.y+(rng(i+30)-.5)*35,v:.4+rng(i+5)*1.4,life:25+rng(i+20)*35,s:2+rng(i)*3,c:['#ffe580','#8de2bf','#fff'][i%3]})}
function update(dt){let x=(keys.ArrowRight||keys.d?1:0)-(keys.ArrowLeft||keys.a?1:0)+joy.x,y=(keys.ArrowDown||keys.s?1:0)-(keys.ArrowUp||keys.w?1:0)+joy.y;if(x||y){let m=Math.hypot(x,y);state.pos.x+=x/m*dt*.17;state.pos.y+=y/m*dt*.17;let q=(state.pos.x/460)**2+(state.pos.y/280)**2;if(q>1){state.pos.x*=.985;state.pos.y*=.985}}}
function loop(t){let dt=Math.min(33,t-last);last=t;if(running)update(dt);drawWorld(t);requestAnimationFrame(loop)}requestAnimationFrame(loop);setInterval(()=>{if(running)save()},5000);
addEventListener('keydown',e=>{keys[e.key]=true;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault()});addEventListener('keyup',e=>keys[e.key]=false);
let joyId=null;function moveJoy(e){const j=$('#joystick'),r=j.getBoundingClientRect(),p=[...e.touches].find(x=>x.identifier===joyId);if(!p)return;let x=p.clientX-(r.left+r.width/2),y=p.clientY-(r.top+r.height/2),m=Math.max(1,Math.hypot(x,y)),lim=35;if(m>lim){x=x/m*lim;y=y/m*lim}joy={x:x/lim,y:y/lim};$('#stick').style.transform=`translate(${x}px,${y}px)`}$('#joystick').addEventListener('touchstart',e=>{joyId=e.changedTouches[0].identifier;moveJoy(e)},{passive:false});$('#joystick').addEventListener('touchmove',e=>{e.preventDefault();moveJoy(e)},{passive:false});$('#joystick').addEventListener('touchend',()=>{joyId=null;joy={x:0,y:0};$('#stick').style.transform=''})
$('#continueBtn').onclick=()=>start(true);$('#newBtn').onclick=()=>{if(hasSave()&&!confirm('Begin a new island? Your current discoveries will be replaced.'))return;start(false)};$('#combineBtn').onclick=combine;$('#discoveryClose').onclick=()=>$('#discovery').classList.add('hidden');$('#journalBtn').onclick=openJournal;$('#titleJournalBtn').onclick=()=>{state=load();openJournal()};$('#settingsBtn').onclick=()=>{$('#settings').classList.remove('hidden');state=load();syncSettings()};$$('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).classList.add('hidden'));$('#soundBtn').onclick=()=>{state.settings.sound=!state.settings.sound;save();$('#soundBtn').textContent=state.settings.sound?'♪':'×'};function syncSettings(){$('#soundSetting').checked=state.settings.sound;$('#motionSetting').checked=state.settings.motion}$('#soundSetting').onchange=e=>{state.settings.sound=e.target.checked;save()};$('#motionSetting').onchange=e=>{state.settings.motion=e.target.checked;save()};$('#resetBtn').onclick=()=>$('#resetConfirm').classList.remove('hidden');$('#resetConfirm').onclick=()=>{localStorage.removeItem(SAVE);location.reload()};$('#finaleClose').onclick=()=>$('#finale').classList.add('hidden');$('#collapseBtn').onclick=()=>{$('#alchemy').classList.add('hidden');$('#alchemyToggle').classList.remove('hidden')};$('#alchemyToggle').onclick=()=>{$('#alchemy').classList.remove('hidden');$('#alchemyToggle').classList.add('hidden')};updateContinue();state=load();drawWorld(0);
})().catch(e=>{document.body.innerHTML=`<div style="padding:40px;color:white"><h1>Alchemy Island</h1><p>The island could not awaken.</p><pre>${e.message}</pre><p>Run this build from a local web server rather than opening the file directly.</p></div>`;console.error(e)});
