(async()=>{'use strict';const APP_VERSION='0.6.0';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const recipes=await fetch('data/recipes.json?v=060').then(r=>r.json());
const seedElements=await fetch('data/elements.json?v=060').then(r=>r.json());
const icons={Mud:'◒',Mist:'≋',Lava:'◉',Steam:'♨',Dust:'⁙',Stone:'⬟',Pond:'◯',Energy:'ϟ',Sand:'∴',Glass:'◇',Clay:'⬢',Brick:'▰',Soil:'▨',Plant:'♧',Tree:'♠',Wood:'▥',Reeds:'〽',Moss:'❧','Primordial Life':'✧',Fish:'><>',Creature:'♞',Insect:'✥',Human:'♙','Sharp Stone':'◢',Tool:'⚒',Plank:'▬',Charcoal:'●','Hot Stone':'◉',Pot:'∪',Wall:'▦',Shelter:'⌂','Campfire Base':'⌄',Campfire:'♨','Glass Pane':'▱',Rope:'§',Raft:'▤',Seeds:'⁘',Crops:'≋',Food:'◈','Cooked Fish':'⋈',Settler:'♟','Metal Ore':'✦',Metal:'⬡','Advanced Tool':'⚙',Electricity:'ϟ'};
const colors={Nature:'#69a75f',Materials:'#a9784c',Life:'#d66f77',Tools:'#637f83',Structures:'#ae7544',Technology:'#bb8ee8',Primordial:'#64aeca'},categoryIcons={Nature:'❧',Materials:'⬡',Life:'✤',Tools:'⚒',Structures:'⌂',Technology:'ϟ'};
Object.assign(icons,{Cloud:'☁',Rain:'☂',Pollen:'⁘',Flower:'✿',Fruit:'●',Flour:'∴',Bread:'▰',Meal:'◉',Basket:'⌗','Fishing Rod':'⌁','Smoked Fish':'⋈',Bird:'⌁',Bee:'✥',Hive:'⬢',Herbivore:'♞',Ash:'⁙',Mortar:'◒',Foundation:'▣',Roof:'⌃',House:'⌂',Well:'⊙',Kiln:'♨',Ceramic:'◡',Wire:'〰',Battery:'▣',Lantern:'◈',Waterwheel:'⊕',Workshop:'⚙',Bridge:'═',Dock:'╦',Cart:'▣',Road:'═',Oasis:'◉',Grove:'♠',Herb:'❧',Medicine:'✚',Pulp:'◫',Paper:'▱',Map:'⌖',Magnet:'∩'});
const elements={...seedElements}; recipes.forEach(r=>elements[r.result]={icon:icons[r.result]||categoryIcons[r.category]||'✦',color:colors[r.category],category:r.category,description:r.text});
const key=(a,b)=>[a,b].sort().join('|'), recipeMap=new Map(recipes.map(r=>[key(r.a,r.b),r]));
const TOTAL=recipes.length, SAVE='alchemy-island-v01'; let state, selected=[], activeCategory='All', journalCategory='All', running=false, last=0, toastTimer, audio;
const defaults=()=>({discovered:['Air','Earth','Fire','Water'],known:[],effects:[],effectTimes:{},attempts:0,success:0,failed:0,pos:{x:0,y:155},settings:{sound:true,motion:false,dayNight:true},settlement:{population:1,food:0,water:0,wood:0,morale:50,lastTick:Date.now(),milestone:false},finale:false,tutorial:true});
function load(){try{const base=defaults(),saved=JSON.parse(localStorage.getItem(SAVE)||'null')||{};return {...base,...saved,settings:{...base.settings,...saved.settings},settlement:{...base.settlement,...saved.settlement}}}catch{return defaults()}}
function save(){localStorage.setItem(SAVE,JSON.stringify(state));const s=$('#saveState');if(s){s.classList.remove('hidden');s.textContent='SAVED';clearTimeout(save.flash);save.flash=setTimeout(()=>s.classList.add('hidden'),1100)}}
function hasSave(){return !!localStorage.getItem(SAVE)}
function tone(type='select'){if(!state?.settings.sound)return; audio??=new(window.AudioContext||window.webkitAudioContext)(); const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);let now=audio.currentTime, f={select:330,fail:120,success:523,discover:659,milestone:392,electric:880}[type]||330;o.frequency.setValueAtTime(f,now);if(type==='discover')o.frequency.exponentialRampToValueAtTime(f*1.7,now+.35);if(type==='electric')o.type='sawtooth';g.gain.setValueAtTime(.001,now);g.gain.exponentialRampToValueAtTime(.12,now+.02);g.gain.exponentialRampToValueAtTime(.001,now+(type==='milestone'?1:.35));o.start(now);o.stop(now+(type==='milestone'?1:.4))}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),1800)}
function start(continueGame=false){state=continueGame?load():defaults();state.effectTimes??={};if(!continueGame)save();$('#titleScreen').classList.add('hidden');$('#hud').classList.remove('hidden');$('#alchemy').classList.remove('hidden');$('#settlementStrip').classList.remove('hidden');if(matchMedia('(pointer:coarse)').matches)$('#joystick').classList.remove('hidden');running=true;renderElements();updateSettlementUI();updateContinue();if(state.tutorial&&!continueGame)opening();}
function updateContinue(){const b=$('#continueBtn');b.disabled=!hasSave()}
async function opening(){const box=$('#opening'),p=$('#openingText');box.classList.remove('hidden');for(const text of ['You remember nothing.','Only four forces answer you.','AIR · EARTH · FIRE · WATER','Combine them.\n\nEARTH + WATER = MUD']){p.innerText=text;await new Promise(r=>setTimeout(r,2100))}box.classList.add('hidden');toast('Try Earth + Water');}
function renderElements(){const cats=['All','Primordial','Nature','Life','Materials','Tools','Structures','Technology'],query=($('#elementSearch')?.value||'').trim().toLowerCase();$('#categories').innerHTML=cats.map(c=>`<button class="${c===activeCategory?'active':''}" data-cat="${c}">${c}</button>`).join('');const list=state.discovered.filter(n=>(activeCategory==='All'||elements[n].category===activeCategory)&&(!query||n.toLowerCase().includes(query))).sort((a,b)=>a.localeCompare(b));$('#elements').innerHTML=list.length?list.map(n=>`<div class="element" data-element="${n}" title="${elements[n].description}"><span class="ico" style="color:${elements[n].color}">${elements[n].icon}</span><b>${n}</b></div>`).join(''):`<div class="empty-elements">No discoveries match.</div>`;if($('#elementCount'))$('#elementCount').textContent=`${list.length} / ${state.discovered.length}`;$$('.element').forEach(el=>el.onclick=()=>selectElement(el.dataset.element));$$('#categories button').forEach(b=>b.onclick=()=>{activeCategory=b.dataset.cat;tone();renderElements()});renderSelected();}
function selectElement(n){tone();if(selected.length>=2)selected=[];selected.push(n);$('#hint').textContent=selected.length===1?'Choose a second element.':'Ready to combine.';renderSelected()}
function renderSelected(){$$('.slot').forEach((s,i)=>{const n=selected[i];s.classList.toggle('filled',!!n);s.innerHTML=n?`<span style="font-size:22px;color:${elements[n].color}">${elements[n].icon}</span><b>${n}</b>`:'Choose';s.onclick=()=>{selected.splice(i,1);renderSelected()}});$('#combineBtn').disabled=selected.length!==2}
function combine(){if(selected.length!==2)return;state.attempts++;const r=recipeMap.get(key(...selected));if(!r){state.failed++;tone('fail');$('#alchemy').animate?.([{transform:'translateX(0)'},{transform:'translateX(-6px)'},{transform:'translateX(6px)'},{transform:'translateX(0)'}],{duration:220});$('#hint').textContent=state.failed%3===0?'A hint: heat transforms earth, plants, and stone.':'Nothing happens…';toast('Nothing happens…');selected=[];renderSelected();save();return}state.success++;const first=!state.discovered.includes(r.result);if(first){state.discovered.push(r.result);state.known.push(key(r.a,r.b));if(r.worldEffect&&!state.effects.includes(r.worldEffect)){state.effects.push(r.worldEffect);state.effectTimes??={};state.effectTimes[r.worldEffect]=Date.now()}save();renderElements();showDiscovery(r)}else{tone('success');toast(`${r.a} + ${r.b} → ${r.result}`)}selected=[];renderSelected();save()}
function showDiscovery(r){if(r.result==='Human')state.settlement.population=Math.max(2,state.settlement.population);if(r.result==='Settler')state.settlement.population=Math.max(3,state.settlement.population);tone(r.worldEffect?'milestone':'discover');$('#discoveryIcon').textContent=elements[r.result].icon;$('#discoveryIcon').style.color=elements[r.result].color;$('#discoveryName').textContent=r.result.toUpperCase();$('#discoveryText').textContent=`“${r.text}”`;$('#discovery').classList.remove('hidden');spawnBurst();updateSettlementUI();if(r.result==='Electricity')setTimeout(finale,1000)}
function finale(){tone('electric');state.finale=true;save();$('#discovery').classList.add('hidden');$('#finale').classList.remove('hidden')}
function openJournal(){renderJournal();$('#journal').classList.remove('hidden')}
function renderJournal(){const cats=['All','Primordial','Nature','Life','Materials','Tools','Structures','Technology'];$('#journalTabs').innerHTML=cats.map(c=>`<button data-jcat="${c}" class="${c===journalCategory?'active':''}">${c}</button>`).join('');const names=['Air','Earth','Fire','Water',...recipes.map(r=>r.result)].filter(n=>journalCategory==='All'||elements[n].category===journalCategory);$('#journalGrid').innerHTML=names.map(n=>state.discovered.includes(n)?`<div class="journal-item"><div class="ico" style="color:${elements[n].color}">${elements[n].icon}</div><b>${n}</b><small>${elements[n].description}</small></div>`:`<div class="journal-item locked">???</div>`).join('');const d=state.discovered.length-4,p=Math.round(d/TOTAL*100);$('#progressText').textContent=`${d} / ${TOTAL} · ${p}% COMPLETE`;$('#progressBar').style.width=p+'%';$('#stats').textContent=`EXPERIMENTS ${state.attempts}  ·  SUCCESSFUL ${state.success}  ·  FAILED ${state.failed}`;$$('[data-jcat]').forEach(b=>b.onclick=()=>{journalCategory=b.dataset.jcat;renderJournal()})}
function settlementCapacity(){return 1+(state.effects.includes('human')?1:0)+(state.effects.includes('shelter')?1:0)+(state.effects.includes('house')?2:0)+(state.effects.includes('settler')?1:0)}
function settlementTick(){if(!state)return;const s=state.settlement,now=Date.now(),steps=Math.min(12,Math.floor((now-s.lastTick)/10000));if(!steps)return;s.lastTick+=steps*10000;for(let i=0;i<steps;i++){if(state.effects.includes('crops'))s.food=Math.min(99,s.food+2);if(state.discovered.includes('Fish'))s.food=Math.min(99,s.food+1);if(state.effects.includes('well')||state.discovered.includes('Pond'))s.water=Math.min(99,s.water+2);if(state.effects.includes('trees'))s.wood=Math.min(99,s.wood+1);const capacity=Math.min(6,settlementCapacity());if(state.effects.includes('settler')&&s.population<capacity&&s.food>=8&&s.water>=8){s.food-=8;s.water-=8;s.population++;tone('milestone');toast('A new settler has joined the shore.')}if(state.effects.includes('settler'))s.morale=Math.max(25,Math.min(100,s.morale+(state.effects.includes('campfire')?1:0)+(state.effects.includes('house')?1:0)-(s.food<3?2:0)))}if(s.population>=5&&s.food>=15&&s.water>=15&&!s.milestone){s.milestone=true;$('#settlementMilestone').classList.remove('hidden');tone('milestone')}save();updateSettlementUI()}
function settlementJobs(){return [{icon:'≋',name:'Tend the farm',who:state.effects.includes('crops')?'Grower':'Waiting for crops'},{icon:'><>',name:'Fish the shallows',who:state.discovered.includes('Fish')?'Fisher':'Waiting for fish'},{icon:'♠',name:'Gather timber',who:state.effects.includes('trees')?'Forager':'Waiting for trees'},{icon:'⚙',name:'Craft at the workshop',who:state.effects.includes('workshop')?'Artisan':'Waiting for workshop'}]}
function updateSettlementUI(){if(!state?.settlement)return;const s=state.settlement;$('#populationChip').textContent=`♟ ${s.population}/${Math.min(6,settlementCapacity())}`;$('#foodChip').textContent=`◆ ${s.food}`;$('#waterChip').textContent=`● ${s.water}`;$('#moraleChip').textContent=`♥ ${s.morale}`}
function openSettlement(){settlementTick();const s=state.settlement,unlocked=state.effects.includes('settler');$('#settlementSummary').innerHTML=`<div class="settlement-hero"><b>${s.population} / ${Math.min(6,settlementCapacity())}</b><span>${unlocked?'SETTLERS CALL THIS ISLAND HOME':'ONE SURVIVOR WAITS FOR COMPANY'}</span></div>`;$('#resourceGrid').innerHTML=`<div class="resource-grid"><div class="resource-card"><b>${s.food}</b><small>FOOD</small></div><div class="resource-card"><b>${s.water}</b><small>WATER</small></div><div class="resource-card"><b>${s.wood}</b><small>TIMBER</small></div><div class="resource-card"><b>${s.morale}</b><small>SPIRIT</small></div></div>`;$('#jobs').innerHTML=settlementJobs().map(j=>`<div class="job-row"><em>${j.icon}</em><b>${j.name}</b><span>${j.who}</span></div>`).join('');$('#settlementHint').textContent=unlocked?'Food, fresh water, and homes allow the community to grow.':'Discover Settler to begin a community.';$('#settlement').classList.remove('hidden');tone('select')}
// World rendering
const canvas=$('#game'),ctx=canvas.getContext('2d'),world={w:1200,h:800},keys={},particles=[],islandImage=new Image();islandImage.src='assets/island-base.png?v=050';let DPR=1,joy={x:0,y:0},nearby=null,moving=false,walkPhase=0,lastTimeBand='';
const landmarks=[
{id:'pond',requires:'Pond',x:-210,y:85,icon:'◯',name:'THE POND',text:'Still water gathers life. Silver shapes now move beneath its surface.'},
{id:'campfire',effect:'campfire',x:-30,y:75,icon:'♨',name:'THE CAMPFIRE',text:'Warmth has changed this place. The fire crackles softly, turning survival into comfort.'},
{id:'shelter',effect:'shelter',x:65,y:-155,icon:'⌂',name:'THE SHELTER',text:'Wood, brick, and intention have made the island feel like home.'},
{id:'crops',effect:'crops',x:205,y:-95,icon:'≋',name:'THE FARM',text:'Ordered rows of green promise that tomorrow will have enough.'},
{id:'raft',effect:'raft',x:-430,y:175,icon:'▤',name:'THE RAFT',text:'Rope binds timber into possibility. Beyond the surf, another shore may be waiting.'},
{id:'electricity',effect:'electricity',x:110,y:-55,icon:'ϟ',name:'THE FIRST LIGHT',text:'A fragile current crosses the wire. For one bright moment, night obeys.'},
{id:'house',effect:'house',x:-120,y:-155,icon:'⌂',name:'THE FIRST HOUSE',text:'A window, a roof, and a door: the settlement now expects a future.'},
{id:'well',effect:'well',x:245,y:35,icon:'⊙',name:'THE WELL',text:'Cool water waits beneath the stone rim, close to every home.'},
{id:'workshop',effect:'workshop',x:245,y:-150,icon:'⚙',name:'THE WORKSHOP',text:'Tools now have a home of their own. New ideas arrive with every hammer blow.'},
{id:'dock',effect:'dock',x:-410,y:100,icon:'╦',name:'THE DOCK',text:'The island has built its first deliberate welcome for the sea.'}
];
function effectProgress(id){const born=state.effectTimes?.[id];if(!born||state.settings.motion)return 1;return Math.min(1,(Date.now()-born)/1800)}
function revealed(id,draw){const p=effectProgress(id);ctx.save();ctx.globalAlpha=.15+.85*p;ctx.translate(0,(1-p)*28);draw();ctx.restore()}
function resize(){DPR=Math.min(devicePixelRatio||1,2);canvas.width=innerWidth*DPR;canvas.height=innerHeight*DPR;canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px'}addEventListener('resize',resize);resize();
function rng(i){return((Math.sin(i*982.451)*43758.5453)%1+1)%1}
function ellipse(x,y,rx,ry,fill,stroke){ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=4;ctx.stroke()}}
function cycleLight(t){return state.settings.dayNight?Math.max(.08,Math.min(1,.54+Math.sin(t/42000)*.58)):1}
function skyLife(t,sx,sy,light){if(light<.5){ctx.fillStyle='#fff8c9';for(let i=0;i<30;i++){const x=rng(i+600)*sx,y=rng(i+650)*sy*.62,r=1+rng(i)*1.5;ctx.globalAlpha=.25+rng(i+2)*.7;ctx.fillRect(x,y,r,r)}ctx.globalAlpha=1}const orbit=t/42000,celestialX=sx*(.5+.44*Math.sin(orbit)),celestialY=sy*(.2-.1*Math.cos(orbit));ctx.shadowBlur=30;ctx.shadowColor=light>.5?'#ffe69a':'#d5e9ff';ellipse(celestialX,celestialY,light>.5?22:17,light>.5?22:17,light>.5?'#ffe9a0':'#dcecff');ctx.shadowBlur=0;if(state.discovered.includes('Cloud')){for(let i=0;i<4;i++){const x=((t*.012+i*sx*.31)%(sx+180))-90,y=85+i*36;ctx.globalAlpha=.18+.25*light;ellipse(x,y,46,14,'#edf5e8');ellipse(x+26,y-8,30,18,'#edf5e8')}ctx.globalAlpha=1}if(state.discovered.includes('Rain')){ctx.strokeStyle='#b8e9ef66';ctx.lineWidth=1.5;for(let i=0;i<45;i++){const x=(rng(i+700)*sx+t*.08)%(sx+30),y=(rng(i+760)*sy+t*.18)%(sy+30);ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-5,y+12);ctx.stroke()}}}
function drawWorld(t){const sx=canvas.width/DPR,sy=canvas.height/DPR,mobile=sx<=700,scale=Math.min(sx/(mobile?1080:1050),sy/(mobile?760:720)),anchorY=mobile?sy*.36:sy/2,light=cycleLight(t);ctx.setTransform(DPR,0,0,DPR,0,0);let g=ctx.createLinearGradient(0,0,0,sy);g.addColorStop(0,light<.45?'#102b49':state.effects.includes('electricity')?'#32717a':'#56b8ca');g.addColorStop(1,light<.45?'#123d59':'#07566b');ctx.fillStyle=g;ctx.fillRect(0,0,sx,sy);skyLife(t,sx,sy,light);ctx.save();ctx.translate(sx/2-state.pos.x*scale,anchorY-state.pos.y*scale);ctx.scale(scale,scale);
// water rings
ctx.strokeStyle='#b8f4e733';ctx.lineWidth=3;for(let i=0;i<14;i++){let y=-330+i*52+Math.sin(t/900+i)*6;ctx.beginPath();ctx.moveTo(-700,y);ctx.quadraticCurveTo(0,y+20,700,y);ctx.stroke()}
if(islandImage.complete&&islandImage.naturalWidth){ctx.save();ctx.beginPath();ctx.ellipse(0,0,520,325,0,0,Math.PI*2);ctx.clip();ctx.drawImage(islandImage,100,40,1384,920,-520,-325,1040,650);ctx.restore()}else{ellipse(0,0,520,325,'#e7c77e','#a7e1b0');ellipse(0,-5,445,270,'#74ad68');ellipse(-30,15,360,215,'#82b96e')}
// crafted resource stones, clustered away from the main path
for(let i=0;i<9;i++){let a=rng(i+40)*6.28,r=245+rng(i+51)*135,x=Math.cos(a)*r,y=Math.sin(a)*r*.62;ellipse(x,y,6+rng(i+2)*7,4+rng(i+3)*5,'#77877d','#4c625c')}
if(state.discovered.includes('Pond')){ellipse(-210,85,48,27,'#52a9a7','#b4e8cb');ctx.strokeStyle='#dff8db88';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(-210,85,28+Math.sin(t/500)*5,12,0,0,6.3);ctx.stroke()}
if(state.effects.includes('vegetation'))revealed('vegetation',()=>{for(let i=0;i<32;i++){let a=rng(i+90)*6.28,r=80+rng(i+110)*330,x=Math.cos(a)*r,y=Math.sin(a)*r*.65;ctx.fillStyle=i%3?'#398e58':'#9dd56d';ctx.beginPath();ctx.arc(x,y,4+rng(i)*5,0,6.3);ctx.fill()}});
if(state.effects.includes('trees'))revealed('trees',()=>{for(let i=0;i<9;i++)tree(-300+i*74+(i%2)*20,-120+(i%3)*80,t,i)});
if(state.effects.includes('crops'))revealed('crops',()=>farm(205,-95));
if(state.effects.includes('shelter'))revealed('shelter',()=>hut(65,-155));
if(state.effects.includes('campfire'))revealed('campfire',()=>campfire(-30,75,t));
if(state.effects.includes('raft'))revealed('raft',()=>raft(-430,175,t));
if(state.effects.includes('human'))revealed('human',()=>drawCommunity(t));
if(state.effects.includes('electricity'))revealed('electricity',()=>generator(110,-55,t));
if(state.effects.includes('flowers'))revealed('flowers',()=>flowers(t));
if(state.effects.includes('birds'))birds(t);
if(state.effects.includes('hive')){ellipse(-210,-98,15,20,'#d9a83e','#65451f');bees(t)}
if(state.effects.includes('herbivore'))herbivore(-265,105,t);
if(state.effects.includes('grove'))revealed('grove',()=>{for(let i=0;i<5;i++)tree(-365+i*38,-55+(i%2)*20,t,i)});
if(state.effects.includes('house'))revealed('house',()=>house(-120,-155));
if(state.effects.includes('well'))revealed('well',()=>well(245,35));
if(state.effects.includes('kiln'))revealed('kiln',()=>kiln(150,120,t));
if(state.effects.includes('waterwheel'))revealed('waterwheel',()=>waterwheel(-180,82,t));
if(state.effects.includes('workshop'))revealed('workshop',()=>workshop(245,-150));
if(state.effects.includes('bridge'))revealed('bridge',()=>bridge(-205,85));
if(state.effects.includes('dock'))revealed('dock',()=>dock(-410,100));
if(state.effects.includes('road'))revealed('road',()=>road());
if(state.discovered.includes('Fish'))fish(t);if(light<.38&&state.effects.includes('vegetation'))fireflies(t);
person(state.pos.x,state.pos.y,'#e9d0a4',t,true);particles.forEach((p,i)=>{p.y-=p.v;p.life--;ctx.globalAlpha=Math.max(0,p.life/40);ellipse(p.x,p.y,p.s,p.s,p.c);ctx.globalAlpha=1;if(p.life<=0)particles.splice(i,1)});ctx.restore();if(light<.82){ctx.fillStyle=`rgba(7,18,48,${(1-light)*.58})`;ctx.fillRect(0,0,sx,sy)}const band=light<.3?'STARLIT NIGHT':light<.52?'TWILIGHT':light<.78?'GOLDEN HOUR':'SUNLIT TIDE';if(band!==lastTimeBand){lastTimeBand=band;const label=$('#timeLabel');if(label)label.textContent=band}}
function tree(x,y,t,i){ctx.fillStyle='#6c4328';ctx.fillRect(x-5,y,10,35);ellipse(x,y-8,25,29,i%2?'#2f7e4f':'#3f9255');ellipse(x-13,y-4,14,17,'#55a862');ellipse(x+14,y-5,14,18,'#4a9e5a')}
function hut(x,y){ctx.fillStyle='#8d562d';ctx.fillRect(x-48,y-10,96,65);ctx.fillStyle='#d59d50';ctx.beginPath();ctx.moveTo(x-62,y);ctx.lineTo(x,y-55);ctx.lineTo(x+62,y);ctx.fill();ctx.fillStyle='#382c25';ctx.fillRect(x-12,y+20,24,35);ctx.fillStyle='#87d5d2';ctx.fillRect(x+23,y+12,18,15)}
function farm(x,y){ctx.fillStyle='#765631';ctx.fillRect(x-70,y-42,140,84);for(let i=0;i<5;i++){ctx.strokeStyle='#afda63';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(x-55+i*27,y-32);ctx.lineTo(x-55+i*27,y+32);ctx.stroke()}}
function campfire(x,y,t){ctx.fillStyle='#5a4130';for(let a=0;a<6.3;a+=1.05)ellipse(x+Math.cos(a)*18,y+Math.sin(a)*9,7,5,'#6f6b5c');ctx.fillStyle='#ffbf44';ctx.beginPath();ctx.moveTo(x-10,y);ctx.quadraticCurveTo(x-18,y-30,x,y-43-Math.sin(t/100)*5);ctx.quadraticCurveTo(x+18,y-25,x+10,y);ctx.fill();ellipse(x,y-3,8,15,'#f26b3d')}
function raft(x,y,t){ctx.save();ctx.translate(x,y+Math.sin(t/500)*4);ctx.rotate(-.12);for(let i=0;i<5;i++){ctx.fillStyle='#82512f';ctx.fillRect(-35+i*15,-17,12,45)}ctx.fillStyle='#dbc88f';ctx.beginPath();ctx.moveTo(0,-65);ctx.lineTo(0,-15);ctx.lineTo(35,-20);ctx.closePath();ctx.fill();ctx.restore()}
function generator(x,y,t){ctx.strokeStyle='#3c2d24';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(x,y);ctx.quadraticCurveTo(x+80,y+50,x+145,y-5);ctx.stroke();ctx.fillStyle='#82643d';ctx.fillRect(x-22,y-20,44,42);ctx.fillStyle='#d8b94f';ctx.beginPath();ctx.arc(x,y,13,0,6.3);ctx.fill();ctx.save();ctx.translate(x,y);ctx.rotate(t/180);ctx.strokeStyle='#394d4d';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(-14,0);ctx.lineTo(14,0);ctx.moveTo(0,-14);ctx.lineTo(0,14);ctx.stroke();ctx.restore();ctx.strokeStyle='#694923';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(x+145,y);ctx.lineTo(x+145,y-55);ctx.stroke();ctx.fillStyle=Math.sin(t/130)>-.3?'#fff7a0':'#534d39';ctx.shadowBlur=25;ctx.shadowColor='#fff28a';ellipse(x+145,y-62,12,16,ctx.fillStyle);ctx.shadowBlur=0}
function flowers(t){for(let i=0;i<20;i++){let a=rng(i+220)*6.28,r=90+rng(i+250)*280,x=Math.cos(a)*r,y=Math.sin(a)*r*.62;ctx.fillStyle=['#f297a8','#ffe17d','#a68ee8'][i%3];ctx.beginPath();ctx.arc(x,y,3+Math.sin(t/400+i),0,6.3);ctx.fill()}}
function birds(t){ctx.strokeStyle='#f4ebd0';ctx.lineWidth=3;for(let i=0;i<4;i++){let x=((t*.035+i*240)%1100)-550,y=-245+i*18;ctx.beginPath();ctx.arc(x-5,y,6,3.6,6);ctx.arc(x+7,y,6,3.3,5.7);ctx.stroke()}}
function bees(t){ctx.fillStyle='#f4c74f';for(let i=0;i<7;i++){let a=t/500+i,x=-210+Math.cos(a*1.7)*28,y=-98+Math.sin(a*2.1)*18;ellipse(x,y,3,2,'#f4c74f')}}
function fish(t){for(let i=0;i<4;i++){let x=-210+Math.sin(t/700+i)*28,y=85+Math.cos(t/850+i*2)*10;ctx.fillStyle='#e9d68b';ctx.beginPath();ctx.moveTo(x+6,y);ctx.lineTo(x-5,y-3);ctx.lineTo(x-5,y+3);ctx.fill()}}
function fireflies(t){ctx.shadowBlur=10;ctx.shadowColor='#eaff80';for(let i=0;i<18;i++){const x=-360+rng(i+820)*720+Math.sin(t/700+i)*9,y=-190+rng(i+850)*360+Math.cos(t/850+i)*7;ctx.globalAlpha=.25+.65*(.5+.5*Math.sin(t/260+i));ellipse(x,y,2.2,2.2,'#efff8a')}ctx.globalAlpha=1;ctx.shadowBlur=0}
function herbivore(x,y,t){ctx.fillStyle='#c9a26b';ctx.fillRect(x-15,y-12,30,18);ellipse(x+18,y-9,9,8,'#c9a26b');ctx.strokeStyle='#4a392d';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(x-9,y+5);ctx.lineTo(x-10,y+17);ctx.moveTo(x+8,y+5);ctx.lineTo(x+9,y+17);ctx.stroke()}
function house(x,y){ctx.fillStyle='#b77b45';ctx.fillRect(x-42,y-8,84,58);ctx.fillStyle='#763f2c';ctx.beginPath();ctx.moveTo(x-54,y);ctx.lineTo(x,y-45);ctx.lineTo(x+54,y);ctx.fill();ctx.fillStyle='#7dc5c5';ctx.fillRect(x-28,y+10,19,18);ctx.fillRect(x+10,y+10,19,18);ctx.fillStyle='#4c3528';ctx.fillRect(x-8,y+22,16,28)}
function well(x,y){ellipse(x,y,25,13,'#727969','#d6c48d');ellipse(x,y-2,17,7,'#286e7b');ctx.strokeStyle='#68452c';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(x-20,y);ctx.lineTo(x-20,y-35);ctx.lineTo(x+20,y-35);ctx.lineTo(x+20,y);ctx.stroke()}
function kiln(x,y,t){ctx.fillStyle='#a85837';ctx.beginPath();ctx.arc(x,y,26,Math.PI,0);ctx.fill();ctx.fillRect(x-26,y,52,25);ellipse(x,y+13,10,12,'#40251e');ctx.fillStyle='#ff8b45';ctx.beginPath();ctx.arc(x,y+15,5+Math.sin(t/150)*2,0,6.3);ctx.fill()}
function waterwheel(x,y,t){ctx.save();ctx.translate(x,y);ctx.rotate(t/450);ctx.strokeStyle='#81532f';ctx.lineWidth=5;ctx.beginPath();ctx.arc(0,0,25,0,6.3);for(let a=0;a<6.3;a+=.78){ctx.moveTo(0,0);ctx.lineTo(Math.cos(a)*25,Math.sin(a)*25)}ctx.stroke();ctx.restore()}
function workshop(x,y){ctx.fillStyle='#6d5d48';ctx.fillRect(x-45,y-5,90,55);ctx.fillStyle='#4a4035';ctx.beginPath();ctx.moveTo(x-55,y);ctx.lineTo(x,y-36);ctx.lineTo(x+55,y);ctx.fill();ctx.fillStyle='#d8a945';ctx.fillRect(x-12,y+12,24,20)}
function bridge(x,y){ctx.strokeStyle='#865631';ctx.lineWidth=9;for(let i=-35;i<=35;i+=12){ctx.beginPath();ctx.moveTo(x+i,y-18);ctx.lineTo(x+i,y+18);ctx.stroke()}}
function dock(x,y){ctx.fillStyle='#81522f';for(let i=0;i<5;i++)ctx.fillRect(x-30+i*15,y-8,12,75)}
function road(){ctx.strokeStyle='#aa986fbb';ctx.lineWidth=12;ctx.beginPath();ctx.moveTo(-280,145);ctx.quadraticCurveTo(0,105,260,92);ctx.stroke()}
function drawCommunity(t){const count=Math.max(1,Math.min(5,state.settlement.population-1)),night=cycleLight(t)<.38&&state.effects.includes('campfire'),routes=night?[[-60,55,-48,62],[-4,48,2,58],[-58,92,-42,88],[-2,92,8,84],[-35,110,-24,105]]:[[-10,58,205,-85],[-160,-125,-300,10],[75,-130,235,-145],[-220,80,-395,125],[30,30,235,35]],colors=['#e7b556','#d66f77','#6fa5c9','#84b96e','#b987ce'];for(let i=0;i<count;i++){const r=routes[i],phase=(Math.sin(t/(2300+i*310)+i*1.7)+1)/2,x=r[0]+(r[2]-r[0])*phase,y=r[1]+(r[3]-r[1])*phase+Math.sin(t/380+i)*4;person(x,y,colors[i],t+i*330)}}
function person(x,y,c,t,player=false){ctx.save();ctx.translate(x,y);const active=player&&moving,bob=active?Math.abs(Math.sin(walkPhase))*3:Math.sin(t/420)*1.2,step=active?Math.sin(walkPhase)*8:0;ctx.globalAlpha=.22;ellipse(0,28,17,6,'#102d2b');ctx.globalAlpha=1;ellipse(0,-19+bob,9,10,'#c98c62');ctx.fillStyle=c;ctx.fillRect(-8,-10+bob,16,25);ctx.strokeStyle='#3f3a35';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(-4,14+bob);ctx.lineTo(-7-step,27);ctx.moveTo(4,14+bob);ctx.lineTo(7+step,27);ctx.stroke();if(player&&state.effects.includes('advanced_tool')){ctx.strokeStyle='#d6d9cc';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(10,-4);ctx.lineTo(20,20);ctx.stroke();ctx.fillStyle='#adb8b6';ctx.fillRect(7,-8,12,7)}ctx.restore()}
function spawnBurst(){for(let i=0;i<28;i++)particles.push({x:state.pos.x+(rng(i)-.5)*60,y:state.pos.y+(rng(i+30)-.5)*35,v:.4+rng(i+5)*1.4,life:25+rng(i+20)*35,s:2+rng(i)*3,c:['#ffe580','#8de2bf','#fff'][i%3]})}
function update(dt){let x=(keys.ArrowRight||keys.d?1:0)-(keys.ArrowLeft||keys.a?1:0)+joy.x,y=(keys.ArrowDown||keys.s?1:0)-(keys.ArrowUp||keys.w?1:0)+joy.y;moving=!!(x||y);if(moving){walkPhase+=dt*.018;let m=Math.hypot(x,y);state.pos.x+=x/m*dt*.17;state.pos.y+=y/m*dt*.17;let q=(state.pos.x/460)**2+(state.pos.y/280)**2;if(q>1){state.pos.x*=.985;state.pos.y*=.985}}const found=landmarks.find(l=>(!l.effect||state.effects.includes(l.effect))&&(!l.requires||state.discovered.includes(l.requires))&&Math.hypot(state.pos.x-l.x,state.pos.y-l.y)<80)||null;if(found?.id!==nearby?.id){nearby=found;const b=$('#interactBtn');b.classList.toggle('hidden',!nearby);if(nearby)b.textContent=`${matchMedia('(pointer:coarse)').matches?'TAP':'E'} · INSPECT ${nearby.name.replace('THE ','')}`}}
function inspectLandmark(){if(!nearby)return;tone('select');$('#landmarkIcon').textContent=nearby.icon;$('#landmarkName').textContent=nearby.name;$('#landmarkText').textContent=nearby.text;$('#landmark').classList.remove('hidden')}
function visibleLandmarks(){return landmarks.filter(l=>(!l.effect||state.effects.includes(l.effect))&&(!l.requires||state.discovered.includes(l.requires)))}
function openMap(){const found=visibleLandmarks(),map=$('#mapCanvas'),pin=(x,y,cls='map-pin')=>`left:${50+x/10.4}%;top:${50+y/6.9}%`;map.innerHTML=found.map(l=>`<div class="map-pin" style="${pin(l.x,l.y)}">✦<span>${l.name.replace('THE ','')}</span></div>`).join('')+`<div class="player-pin" style="${pin(state.pos.x,state.pos.y)}"></div>`;$('#mapProgress').textContent=`${found.length} LANDMARK${found.length===1?'':'S'} CHARTED`;$('#map').classList.remove('hidden');tone('select')}
async function checkForUpdate(){const button=$('#updateBtn'),status=$('#updateStatus');button.disabled=true;status.textContent='Checking the island archives…';try{const remote=await fetch(`version.json?t=${Date.now()}`,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error('offline');return r.json()});if('serviceWorker'in navigator){const reg=await navigator.serviceWorker.getRegistration();await reg?.update()}if(remote.version!==APP_VERSION){status.textContent=`Update v${remote.version} found. Reloading…`;setTimeout(()=>location.replace(`./?updated=${remote.version}&t=${Date.now()}`),700)}else{status.textContent=`You have the newest version: v${APP_VERSION}.`;button.textContent='REFRESH GAME';button.onclick=()=>location.replace(`./?refresh=${Date.now()}`)}}catch{status.textContent='Unable to check. You may be offline.'}finally{button.disabled=false}}
function loop(t){let dt=Math.min(33,t-last);last=t;if(running)update(dt);drawWorld(t);requestAnimationFrame(loop)}requestAnimationFrame(loop);setInterval(()=>{if(running){settlementTick();save()}},5000);
addEventListener('keydown',e=>{keys[e.key]=true;if(e.key.toLowerCase()==='e')inspectLandmark();if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault()});addEventListener('keyup',e=>keys[e.key]=false);
let joyId=null;function moveJoy(e){const j=$('#joystick'),r=j.getBoundingClientRect(),p=[...e.touches].find(x=>x.identifier===joyId);if(!p)return;let x=p.clientX-(r.left+r.width/2),y=p.clientY-(r.top+r.height/2),m=Math.max(1,Math.hypot(x,y)),lim=35;if(m>lim){x=x/m*lim;y=y/m*lim}joy={x:x/lim,y:y/lim};$('#stick').style.transform=`translate(${x}px,${y}px)`}$('#joystick').addEventListener('touchstart',e=>{joyId=e.changedTouches[0].identifier;moveJoy(e)},{passive:false});$('#joystick').addEventListener('touchmove',e=>{e.preventDefault();moveJoy(e)},{passive:false});$('#joystick').addEventListener('touchend',()=>{joyId=null;joy={x:0,y:0};$('#stick').style.transform=''})
$('#continueBtn').onclick=()=>start(true);$('#newBtn').onclick=()=>{if(hasSave()&&!confirm('Begin a new island? Your current discoveries will be replaced.'))return;start(false)};$('#combineBtn').onclick=combine;$('#discoveryClose').onclick=()=>$('#discovery').classList.add('hidden');$('#journalBtn').onclick=openJournal;$('#mapBtn').onclick=openMap;$('#titleJournalBtn').onclick=()=>{state=load();openJournal()};$('#settingsBtn').onclick=()=>{$('#settings').classList.remove('hidden');state=load();syncSettings()};$$('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).classList.add('hidden'));$('#soundBtn').onclick=()=>{state.settings.sound=!state.settings.sound;save();$('#soundBtn').textContent=state.settings.sound?'♪':'×'};function syncSettings(){$('#soundSetting').checked=state.settings.sound;$('#motionSetting').checked=state.settings.motion;$('#cycleSetting').checked=state.settings.dayNight}$('#soundSetting').onchange=e=>{state.settings.sound=e.target.checked;save()};$('#motionSetting').onchange=e=>{state.settings.motion=e.target.checked;save()};$('#cycleSetting').onchange=e=>{state.settings.dayNight=e.target.checked;save()};$('#updateBtn').onclick=checkForUpdate;$('#resetBtn').onclick=()=>$('#resetConfirm').classList.remove('hidden');$('#resetConfirm').onclick=()=>{localStorage.removeItem(SAVE);location.reload()};$('#finaleClose').onclick=()=>$('#finale').classList.add('hidden');$('#collapseBtn').onclick=()=>{$('#alchemy').classList.add('hidden');$('#alchemyToggle').classList.remove('hidden')};$('#alchemyToggle').onclick=()=>{$('#alchemy').classList.remove('hidden');$('#alchemyToggle').classList.add('hidden')};$('#interactBtn').onclick=inspectLandmark;updateContinue();state=load();drawWorld(0);if('serviceWorker'in navigator){navigator.serviceWorker.register('./sw.js').then(r=>r.update()).catch(()=>{});let refreshing=false;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(refreshing)return;refreshing=true;location.reload()})}
$('#gameSettingsBtn').onclick=()=>{$('#settings').classList.remove('hidden');state=load();syncSettings()};
$('#settlementBtn').onclick=openSettlement;$('#milestoneClose').onclick=()=>$('#settlementMilestone').classList.add('hidden');
$('#elementSearch').oninput=renderElements;
})().catch(e=>{document.body.innerHTML=`<div style="padding:40px;color:white"><h1>Alchemy Island</h1><p>The island could not awaken.</p><pre>${e.message}</pre><p>Run this build from a local web server rather than opening the file directly.</p></div>`;console.error(e)});
